[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "multi"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
bsc = "${BSC_RPC_URL}"
base = "${BASE_RPC_URL}"
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545"
base_sepolia = "https://sepolia.base.org"

[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
